### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Sophia-Gold**
Forked to keep a version with notes for creating slides

### CODE REVIEW

**Comment by delaray** [comment]
This is great. Is this intended

**Comment by delaray** [comment]
Is intended to cover 2 days or just 1?

**Comment by Sophia-Gold** [comment]
Please keep this PR open so we can use it as an outline when creating slides for the first day of the advanced track.

**Comment by Sophia-Gold** [comment]
Closing since we moved the outline into the slides folder.

**Pull request closed without merging**
